import { readFileSync } from 'node:fs';
import { Game } from '../src/core/game';
import { Searcher } from '../src/engine/search';
import { defaultEvalParams, defaultSearchOptions } from '../src/engine/params';
const r = JSON.parse(readFileSync('results/muwyjg6z8ac586.json', 'utf8'));
const g0 = r.games.find((g: any) => g.reason === 'max-moves');
const g = new Game(g0.startFen);
for (const m of g0.moves.slice(0, g0.moves.length - 30)) g.playUci(m.uci);
console.log(g.fen);
const s = new Searcher(defaultEvalParams(), defaultSearchOptions());
const res = s.search(g.pos, { timeMs: 100 }, (i) => console.log(i.depth, i.score, i.mate, i.nodes, i.pv.slice(0, 8).join(' ')));
console.log(res.bestMove, res.score, res.mate, res.completedDepth, res.nodes);
const t0 = performance.now();
const s2 = new Searcher(defaultEvalParams(), defaultSearchOptions());
const r2 = s2.search(g.pos, { depth: 8 });
console.log('d8', r2.bestMove, r2.score, r2.mate, r2.nodes, (performance.now() - t0).toFixed(0), 'ms', r2.qnodes);
import { parseFen } from '../src/core/fen';
const p3 = parseFen(g.fen);
const t1 = performance.now();
const r3 = new Searcher(defaultEvalParams(), defaultSearchOptions()).search(p3, { depth: 8 });
console.log('fresh pos d8', r3.bestMove, r3.score, r3.mate, r3.nodes, (performance.now() - t1).toFixed(0), 'ms');
